version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "main"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.5.5"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.5.6"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.6.0"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.6.1"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.6.2"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.6.3"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.7.0"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.7.1"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
    target-branch: "1.8.0"

