site:
  title: Longhorn documentation
  url: /
  start_page: 1.7.0@longhorn-product-docs::index.adoc

content:
  sources:
    - url: ../longhorn-product-docs
      branches: [1.8.0, 1.7.1, 1.7.0, 1.6.3 1.6.1 1.6.0 1.5.6 1.5.5]

ui:
  bundle:
    url: style_package/uix.zip
    #url: https://github.com/uyuni-project/uyuni-docs/blob/master/branding/default-ui/suma/ui-bundle.zip?raw=true
    snapshot: true
  #supplemental_files: ./susecom-2023

asciidoc:
  extensions:
    - asciidoctor-kroki


output:
  dir: build/site
